name: Manual Hello World

on:
  workflow_dispatch: {}

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
      - name: Print Goddbye World
        run: echo "Goodbye, World!"
